---
version: '3.3'
services:
  jenkins:
  image: jenkins
  restart: unless-stopped
  privileged: true
  user: root
  ports:
    - 8081:8081
  container_name: jenkins
  volumes:
    - ~/jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/local/bin/docker
